[package]
name = "md4_test"
version = "0.1.0"
authors = ["pranav"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md4 = "0.9.0"
